### ISSUE TITLE
请问毫无编程基础 如何使用这个

### ISSUE THREAD

**Issue by spikyhair** [magicdawn/yun-playlist-downloader#15]
你好。我毫无编程基础，搜索到这里。 这个工具要怎么使用呢？

下载了 node-v6.95-win-x64.zip， 下载的对吗？
解压后 这node似乎是不用/不能安装？
也下载了您写的工具，但是好像也是不能直接安装

对一个完全的小白来说，使用这个工具的话
具体的步骤是怎样呢？

非常感谢

**Comment by magicdawn** [comment]
1. http://www.runoob.com/nodejs/nodejs-install-setup.html
2. 打开命令行, 运行 `npm install yun-playlist-downloader -g`
3. 使用 `yun 歌单地址` 下载

**Comment by spikyhair** [comment]
我按您给的地址安装了node js 4.43

之后运行了npm install yun-playlist-downloader -g
发现安装错误 
![node](https://cloud.githubusercontent.com/assets/26085169/23458792/97b83c56-feb8-11e6-93fc-83841d28172d.JPG)

这是因为 yun-playlist-downloader 放置的位置不对吗还是怎样
yun-playlist-downloader是要以zip还是解压后的形式放在哪个目录呢？

**Comment by magicdawn** [comment]
ECONNRESET 是网络查, 可以使用 cnpm 装

1. `npm install -g cnpm --registry=https://registry.npm.taobao.org`
2. `cnpm i yun-playlist-downloader -g`

**Comment by spikyhair** [comment]
感谢你的耐心帮助 已安装好。下了一些专辑了。

但是发现有的还是不能下载

![yun3](https://cloud.githubusercontent.com/assets/26085169/23506019/077f1f00-ff81-11e6-9050-153a225252cf.JPG)

**Comment by magicdawn** [comment]
> 但是发现有的还是不能下载
有些是需要付费的 ? 这个也没辙...
