### ISSUE TITLE
请问下载的歌曲可以自定义路径吗?

### ISSUE THREAD

**Issue by Xeon-gAp** [magicdawn/yun-playlist-downloader#17]

**Comment by magicdawn** [comment]
see https://github.com/magicdawn/yun-playlist-downloader#自定义文件名--f--format

**Comment by Xeon-gAp** [comment]
不好意思了, 其实看不太懂, 比如说我想指定下载路径为D盘的根目录, 那么指令应该怎么写呢?

**Comment by magicdawn** [comment]
cd 到 D 盘, 即可, 然后运行即可
