### ISSUE TITLE
有网易云下载歌曲的url么

### ISSUE THREAD

**Issue by wenbochang888** [magicdawn/yun-playlist-downloader#19]
代码中用到了网易云真是的下载地址么？
比如 ： http://m7.music.126.net/20170730175809/1d3f912eb87e42cd6d6bcf008c07a09e/ymusic/73ad/4065/4df4/f8b3b410889cf0eddab5d5d0b3b2a702.mp3
类似这种的，谢谢

**Comment by magicdawn** [comment]
是啊 ... 不然怎么下载 ...

**Comment by wenbochang888** [comment]
网易云有两个字段 你是怎么解密出来的？ 能把解密的源码分享一下么？最近在做一个东西，一直搞不定url地址

**Comment by magicdawn** [comment]
我偷了个懒, 拿 nightmare 开了个伪浏览器, 调用它自己的加密方法

https://github.com/magicdawn/yun-playlist-downloader/issues/5#issuecomment-184102982
https://github.com/magicdawn/yun-playlist-downloader/blob/v1.0.0/lib/night.js#L43-L49

**Comment by magicdawn** [comment]
要研究解密方法看看其他的云音乐项目
像 NeteaseMusicApi 是自己实现的

**Comment by wenbochang888** [comment]
向js大佬低头。我看过好几个项目，网易云加密方式变了，都用不了了。不过多谢了
