### ISSUE TITLE
老大，什么时候更新下

### ISSUE THREAD

**Issue by ncuu** [magicdawn/yun-playlist-downloader#20]
yun http://music.163.com/#/playlist?id=12583200

当前参数
concurrency: 5
timeout:     3
max-times:   3
quality:     320
format:      :name/:singer - :songName.:ext
skip:        true

SyntaxError: Unexpected token H in JSON at position 0
    at JSON.parse (<anonymous>)
    at Object.exports.getSongs (C:\Users\Administrator.USER-20171126FM\AppData\R
oaming\npm\node_modules\yun-playlist-downloader\lib\index.js:236:20)
    at main (C:\Users\Administrator.USER-20171126FM\AppData\Roaming\npm\node_mod
ules\yun-playlist-downloader\bin\yun:116:27)
    at <anonymous>

**Comment by ncuu** [comment]
出错了

**Comment by magicdawn** [comment]
v1.1.0 已发布

https://github.com/magicdawn/yun-playlist-downloader/blob/master/CHANGELOG.md#2018-01-19-v110
