### ISSUE TITLE
Cannot read property 'filter' of undefined

### ISSUE THREAD

**Issue by NAMEs** [magicdawn/yun-playlist-downloader#23]
TypeError: Cannot read property 'filter' of undefined
    at Object.exports.getSongs (/usr/local/lib/node_modules/yun-playlist-downloader/lib/index.js:238:15)
    at <anonymous>

**Comment by halfu** [comment]
这样代码如下：json = json.filter(s => s.url)
根据readme的描述，这个程序依赖rc
我安装了rc 1.2.8依然是这个错误。

**Comment by magicdawn** [comment]
```
yun:api:playurl:music-api POST result: {"code":-460,"msg":"Cheating"}
```

用的这个模块 https://github.com/LIU9293/musicAPI
网易给封了 貌似

**Comment by magicdawn** [comment]
v1.4.0 已发布
> music-api 无法使用, 经排查, 获取下载地址接口需要带 cookie 访问, 暂时切回 nightmare
