### ISSUE TITLE
树莓派3B+无法使用，报错如下

### ISSUE THREAD

**Issue by carloswear** [magicdawn/yun-playlist-downloader#24]
运行环境：
Linux OSMC32G 4.14.34-5-osmc 基于Debian
nodejs：v8.12.0
npm：6.4.1
electron：v1.8.8-linux-arm（安装时默认的版本）
nodejs和npm为已编译的arm7版本
electron尝试默认版本和手动安装最新版本，安装成功，仍旧报错

报错如下：
`osmc@OSMC32G:~/Music$ sudo yun https://music.163.com/#/playlist?id=2418285525

当前参数
concurrency: 5
timeout:     3
max-times:   3
quality:     320
format:      :name/:singer - :songName.:ext
skip:        true

RequestError: Error: connect ETIMEDOUT 59.111.160.197:443
    at new RequestError (/usr/lib/node_modules/yun-playlist-downloader/node_modules/request-promise-core/lib/errors.js:14:15)
    at Request.plumbing.callback (/usr/lib/node_modules/yun-playlist-downloader/node_modules/request-promise-core/lib/plumbing.js:87:29)
    at Request.RP$callback [as _callback] (/usr/lib/node_modules/yun-playlist-downloader/node_modules/request-promise-core/lib/plumbing.js:46:31)
    at self.callback (/usr/lib/node_modules/yun-playlist-downloader/node_modules/request/request.js:185:22)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at Request.onRequestError (/usr/lib/node_modules/yun-playlist-downloader/node_modules/request/request.js:881:8)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at TLSSocket.socketErrorListener (_http_client.js:387:9)
    at emitOne (events.js:116:13)
    at TLSSocket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:66:8)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
    at process._tickCallback (internal/process/next_tick.js:181:9)
`
在Windows环境下测试同一链接无问题~

**Comment by carloswear** [comment]
osmc@OSMC32G:~/test$ npm list -g --depth 1
/usr/lib
├─┬ async@2.6.1
│ └── lodash@4.17.11
├── await@0.2.6
├─┬ electron@3.0.0
│ ├── @types/node@8.10.29
│ ├── electron-download@4.1.1
│ └── extract-zip@1.6.7
├─┬ npm@6.4.1
│ ├── abbrev@1.1.1
│ ├── ansicolors@0.3.2
│ ├── ansistyles@0.1.3
│ ├── aproba@1.2.0
│ ├── archy@1.0.0
│ ├── bin-links@1.1.2
│ ├── bluebird@3.5.1
│ ├── byte-size@4.0.3
│ ├── cacache@11.2.0
│ ├── call-limit@1.1.0
│ ├── chownr@1.0.1
│ ├── ci-info@1.4.0
│ ├── cli-columns@3.1.2
│ ├── cli-table3@0.5.0
│ ├── cmd-shim@2.0.2
│ ├── columnify@1.5.4
│ ├── config-chain@1.1.11
│ ├── debuglog@1.0.1
│ ├── detect-indent@5.0.0
│ ├── detect-newline@2.1.0
│ ├── dezalgo@1.0.3
│ ├── editor@1.0.0
│ ├── figgy-pudding@3.4.1
│ ├── find-npm-prefix@1.0.2
│ ├── fs-vacuum@1.2.10
│ ├── fs-write-stream-atomic@1.0.10
│ ├── gentle-fs@2.0.1
│ ├── glob@7.1.2
│ ├── graceful-fs@4.1.11
│ ├── has-unicode@2.0.1
│ ├── hosted-git-info@2.7.1
│ ├── iferr@1.0.2
│ ├── imurmurhash@0.1.4
│ ├── inflight@1.0.6
│ ├── inherits@2.0.3
│ ├── ini@1.3.5
│ ├── init-package-json@1.10.3
│ ├── is-cidr@2.0.6
│ ├── json-parse-better-errors@1.0.2
│ ├── JSONStream@1.3.4
│ ├── lazy-property@1.0.0
│ ├── libcipm@2.0.2
│ ├── libnpmhook@4.0.1
│ ├── libnpx@10.2.0
│ ├── lock-verify@2.0.2
│ ├── lockfile@1.0.4
│ ├── lodash._baseindexof@3.1.0
│ ├── lodash._baseuniq@4.6.0
│ ├── lodash._bindcallback@3.0.1
│ ├── lodash._cacheindexof@3.0.2
│ ├── lodash._createcache@3.1.2
│ ├── lodash._getnative@3.9.1
│ ├── lodash.clonedeep@4.5.0
│ ├── lodash.restparam@3.6.1
│ ├── lodash.union@4.6.0
│ ├── lodash.uniq@4.5.0
│ ├── lodash.without@4.4.0
│ ├── lru-cache@4.1.3
│ ├── meant@1.0.1
│ ├── mississippi@3.0.0
│ ├── mkdirp@0.5.1
│ ├── move-concurrently@1.0.1
│ ├── node-gyp@3.8.0
│ ├── nopt@4.0.1
│ ├── normalize-package-data@2.4.0
│ ├── npm-audit-report@1.3.1
│ ├── npm-cache-filename@1.0.2
│ ├── npm-install-checks@3.0.0
│ ├── npm-lifecycle@2.1.0
│ ├── npm-package-arg@6.1.0
│ ├── npm-packlist@1.1.11
│ ├── npm-pick-manifest@2.1.0
│ ├── npm-profile@3.0.2
│ ├── npm-registry-client@8.6.0
│ ├── npm-registry-fetch@1.1.0
│ ├── npm-user-validate@1.0.0
│ ├── npmlog@4.1.2
│ ├── once@1.4.0
│ ├── opener@1.5.0
│ ├── osenv@0.1.5
│ ├── pacote@8.1.6
│ ├── path-is-inside@1.0.2
│ ├── promise-inflight@1.0.1
│ ├── qrcode-terminal@0.12.0
│ ├── query-string@6.1.0
│ ├── qw@1.0.1
│ ├── read@1.0.7
│ ├── read-cmd-shim@1.0.1
│ ├── read-installed@4.0.3
│ ├── read-package-json@2.0.13
│ ├── read-package-tree@5.2.1
│ ├── readable-stream@2.3.6
│ ├── readdir-scoped-modules@1.0.2
│ ├── request@2.88.0
│ ├── retry@0.12.0
│ ├── rimraf@2.6.2
│ ├── safe-buffer@5.1.2
│ ├── semver@5.5.0
│ ├── sha@2.0.1
│ ├── slide@1.1.6
│ ├── sorted-object@2.0.1
│ ├── sorted-union-stream@2.1.3
│ ├── ssri@6.0.0
│ ├── stringify-package@1.0.0
│ ├── tar@4.4.6
│ ├── text-table@0.2.0
│ ├── tiny-relative-date@1.3.0
│ ├── uid-number@0.0.6
│ ├── umask@1.1.0
│ ├── unique-filename@1.1.0
│ ├── unpipe@1.0.0
│ ├── update-notifier@2.5.0
│ ├── uuid@3.3.2
│ ├── validate-npm-package-license@3.0.4
│ ├── validate-npm-package-name@3.0.0
│ ├── which@1.3.1
│ ├── worker-farm@1.6.0
│ └── write-file-atomic@2.3.0
└─┬ yun-playlist-downloader@1.4.0
  ├── @magicdawn/music-api@0.3.11
  ├── cheerio@0.22.0
  ├── debug@3.2.5
  ├── fs-extra@5.0.0
  ├── humanize-duration@3.15.3
  ├── lodash@4.17.11
  ├── log-reject-error@0.0.2
  ├── log-symbols@2.2.0
  ├── moment@2.22.2
  ├── nightmare@3.0.1
  ├── promise.map@0.0.2
  ├── promise.retry@0.1.0
  ├── rc@1.2.8
  ├── request@2.88.0
  ├── request-promise@4.2.2
  ├── sanitize-filename@1.6.1
  └── yargs@11.1.0

**Comment by carloswear** [comment]
查看了下，应该是electron没有正确安装。默认下载的版本是arm的，树莓派需要arm7l，导致程序无法调用electron。貌似修改install.js会有效~没有编程基础，不晓得该咋改。: (

**Comment by Tarhyru** [comment]
立刻结束的原因是..基于electron的下载似乎有问题..
没有任何错误信息返回，但是，作者还制作了基于网易云接口的...
https://github.com/magicdawn/yun-playlist-downloader/blob/e2387bd785bc7b1579586b4ff71f723593164df8/lib/api/playurl/index.js#L6

把这个注释解开..
再把下面那个引用的注释注释掉..就能正常在树莓派上使用。

**Comment by chujionglie** [comment]
> 目前是出现窗口后无任务，立即结束
> osmc@OSMC32G:~/Music$ sudo yun https://music.163.com/#/playlist?id=2418285525
> 
> 当前参数
> concurrency: 5
> timeout: 3
> max-times: 3
> quality: 320
> format: :name/:singer - :songName.:ext
> skip: true
> 
> osmc@OSMC32G:~/Music$

我也是一模一样的问题，Ubuntu server 18.04，运行了以后显示参数内容，并不开始下载。Windows下使用正常。

**Comment by magicdawn** [comment]
现在有 NeteaseCloudMusicApi, nightmare 已经去除(v3.0.0).
