### ISSUE TITLE
名称中带有特殊字符的歌单无法下载

### ISSUE THREAD

**Issue by nobody-65534** [magicdawn/yun-playlist-downloader#25]
例如：https://music.163.com/#/playlist?id=144617098
带有字符'|'，Window下不能建立文件夹，直接失败。

**Comment by magicdawn** [comment]
em...
忘了给 `:name` 加 sanitize 了, 后面切到 `filenamify` 一起处理
https://github.com/magicdawn/yun-playlist-downloader/blob/master/lib/index.js#L287
