### ISSUE TITLE
基于night的下载，不正常?

### ISSUE THREAD

**Issue by Tarhyru** [magicdawn/yun-playlist-downloader#27]
尝试下载歌单，输出了一些信息，发现..
利用night 下载的方式似乎是挂了..
https://github.com/magicdawn/yun-playlist-downloader/blob/e2387bd785bc7b1579586b4ff71f723593164df8/lib/api/playurl/night.js#L45

这一步直接跳出了...
也没有任何错误弹出..
一开始我以为是运行环境的问题（最开始我跑在树莓派上），但是...
我换到阿里云的centos7上依旧不工作...
不过，把方式换成基于sdk下载，就能正常运作

**Comment by StarryFK** [comment]
用的 Windows Subsystem for Linux，在其中的 Debian 上运行有相同的问题，用问主所提到的方法切换成 sdk 下载之后就能使用了，不过在 Windows 上安装的 Nodejs 倒是可以直接使用本程序而没有异常情况。

**Comment by magicdawn** [comment]
em...可以看下更新日志...

> ## 2018-08-26 v1.4.0
> - music-api 无法使用, 经排查, 获取下载地址接口需要带 cookie 访问, 暂时切回 nightmare

这个需要可能是需要桌面环境, nightmare 依赖 electron.
我自己的用 music-api 网易云音乐返回不太正常, 所以就切了.
