### ISSUE TITLE
windows下无法下载

### ISSUE THREAD

**Issue by noeagles** [magicdawn/yun-playlist-downloader#28]
截图如下
![default](https://user-images.githubusercontent.com/23616523/47735029-92c70b00-dca6-11e8-8332-ca01d3641fb4.PNG)

**Comment by magicdawn** [comment]
```
playlist\?id\=xxx
```
这个应该是 shell escape, 而且是我将不带 `\` 粘贴到 mac iterm2 自动生成的

比如在 mac/linux 可以用单引号, 就不用 escape
```
yun 'xxx/playlist?id=1234'
```

windows的话不太清楚, 建议你直接从浏览器粘贴 url, 而不要手敲这个...
