### ISSUE TITLE
能批量下载.csv文件数据的链接吗

### ISSUE THREAD

**Issue by vinyo** [magicdawn/yun-playlist-downloader#29]
https://music.163.com/#/song?id=28987626
https://music.163.com/#/song?id=28987626
https://music.163.com/#/song?id=28987626
https://music.163.com/#/song?id=28987626
如这些数据

**Comment by magicdawn** [comment]
Way 1
em... 这个仓库提供了 lib 哈, 你可以写代码去调用这个

Way 2
你可以将歌曲新建成歌单, 然后用这个命令行下载
