### ISSUE TITLE
是不是已经凉了？

### ISSUE THREAD

**Issue by CoderTonyChan** [magicdawn/yun-playlist-downloader#30]
这个list
https://music.163.com/m/playlist?id=2553442303
```
正在下载『2004华语乐坛有多“疯狂”？』,请稍候...
internal/streams/legacy.js:57
      throw er; // Unhandled stream error in pipe.
```

**Comment by magicdawn** [comment]
![image](https://user-images.githubusercontent.com/4067115/59160937-8a716100-8b0e-11e9-9161-38b73cee4fbf.png)

猜测, 你网络问题?

**Comment by magicdawn** [comment]
可能是这个问号 #25
