### ISSUE TITLE
能增加无损音乐的下载吗？

### ISSUE THREAD

**Issue by dpeng** [magicdawn/yun-playlist-downloader#32]
现在貌似只支持320码率的下载，能不能增加无损的下载，wav,flac随便什么格式都行，多谢啦

**Comment by magicdawn** [comment]
无损需要 vip 吧 🐶 

![image](https://user-images.githubusercontent.com/4067115/96361718-9fc2ba80-115a-11eb-8dff-c2a82ef5ee5b.png)

**Comment by incubus-ohy** [comment]
> 无损需要 vip 吧 🐶
> 
> ![image](https://user-images.githubusercontent.com/4067115/96361718-9fc2ba80-115a-11eb-8dff-c2a82ef5ee5b.png)

可是项目本身不就是    本项目不支持越权使用, VIP 歌曲请开通 VIP 后结合
