### ISSUE TITLE
很抱歉，不知道为何安装不上

### ISSUE THREAD

**Issue by aumk** [magicdawn/yun-playlist-downloader#34]
Windows，nodejs12环境，安装失败
Windows，WSL Ubuntu 19.10+nodejs12环境，安装失败
Ubuntu 19.10，nodejs12环境，安装失败
是nodejs版本问题吗？
放上错误信息

> @magicdawn/get-cursor-position@1.0.5 install /usr/lib/node_modules/yun-playlist-downloader/node_modules/@magicdawn/get-cursor-position
> node-gyp rebuild

gyp WARN EACCES current user ("nobody") does not have permission to access the dev dir "/root/.cache/node-gyp/12.13.0"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/usr/lib/node_modules/yun-playlist-downloader/node_modules/@magicdawn/get-cursor-position/.node-gyp"
gyp WARN install got an error, rolling back install
gyp WARN install got an error, rolling back install
gyp ERR! configure error
gyp ERR! stack Error: EACCES: permission denied, mkdir '/usr/lib/node_modules/yun-playlist-downloader/node_modules/@magicdawn/get-cursor-position/.node-gyp'
gyp ERR! System Linux 4.4.0-18362-Microsoft
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/lib/node_modules/yun-playlist-downloader/node_modules/@magicdawn/get-cursor-position
gyp ERR! node -v v12.13.0
gyp ERR! node-gyp -v v5.0.5
gyp ERR! not ok
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @magicdawn/get-cursor-position@1.0.5 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @magicdawn/get-cursor-position@1.0.5 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-11-28T16_41_56_502Z-debug.log

**Comment by magicdawn** [comment]
gyp ERR! stack Error: EACCES: permission denied, mkdir '/usr/lib/node_modules/yun-playlist-downloader/node_modules/@magicdawn/get-cursor-position/.node-gyp'

权限问题, 可以尝试切换账户啥的

**Comment by dingxiaobo** [comment]
可以用这个命令装  `npm i pos -g --unsafe-perm`

**Comment by aumk** [comment]
> 可以用这个命令装 `npm i pos -g --unsafe-perm`

加上--unsafe-perm倒是绕过了权限问题
npm i yun-playlist-downloader -g  --unsafe-perm
但又出了错误
/usr/bin/ld: final link failed: nonrepresentable section on output
collect2: error: ld returned 1 exit status
make: *** [pos.target.mk:137: Release/obj.target/pos.node] Error 1
make: Leaving directory '/usr/lib/node_modules/yun-playlist-downloader/node_modules/@magicdawn/get-cursor-position/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:210:5)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
gyp ERR! System Linux 4.19.0-6-amd64
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/lib/node_modules/yun-playlist-downloader/node_modules/@magicdawn/get-cursor-position
gyp ERR! node -v v12.13.1
gyp ERR! node-gyp -v v5.0.5
gyp ERR! not ok
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @magicdawn/get-cursor-position@1.0.5 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @magicdawn/get-cursor-position@1.0.5 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Comment by magicdawn** [comment]
我加了一个 ascii-progress 实现了一个滚动条效果

![image](https://user-images.githubusercontent.com/4067115/70019143-48a80b80-15c3-11ea-9c82-1d76e2ab4d5b.png)

但是这个包需要 build, 我看把它变成 optionalDependencies 能用不

**Comment by magicdawn** [comment]
需要添加一下参数 `-p false`, 关闭进度条显示

![image](https://user-images.githubusercontent.com/4067115/70019561-9e30e800-15c4-11ea-8bba-a268edc13e3a.png)

**Comment by magicdawn** [comment]
yun-playlist-downloader@2.2.0 已发布

**Comment by DysaniazzZ** [comment]
> 需要添加一下参数 `-p false`, 关闭进度条显示
> 
> ![image](https://user-images.githubusercontent.com/4067115/70019561-9e30e800-15c4-11ea-8bba-a268edc13e3a.png)

带进度的下载不了，会报错，把这个关了（加上 `-p false` 就可以了）：

```
Error: Cannot find module '@magicdawn/ascii-progress'
Require stack:
- /usr/local/lib/node_modules/yun-playlist-downloader/lib/index.js
- /usr/local/lib/node_modules/yun-playlist-downloader/lib/bin.js
- /usr/local/lib/node_modules/yun-playlist-downloader/bin/yun
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:1029:15)
    at Function.Module._load (internal/modules/cjs/loader.js:898:27)
    at Module.require (internal/modules/cjs/loader.js:1089:19)
    at require (internal/modules/cjs/helpers.js:73:18)
    at Object.exports.downloadSongWithProgress (/usr/local/lib/node_modules/yun-playlist-downloader/lib/index.js:41:25)
    at Object.exports.downloadSong (/usr/local/lib/node_modules/yun-playlist-downloader/lib/index.js:34:24)
    at Object.<anonymous> (/usr/local/lib/node_modules/yun-playlist-downloader/lib/bin.js:162:24)
    at /usr/local/lib/node_modules/yun-playlist-downloader/node_modules/promise.map/src/index.js:29:30
    at replenish (/usr/local/lib/node_modules/yun-playlist-downloader/node_modules/promise.map/src/index.js:38:11)
    at /usr/local/lib/node_modules/yun-playlist-downloader/node_modules/promise.map/src/index.js:40:7
```

**Comment by DysaniazzZ** [comment]
-p false works, thx bro
