### ISSUE TITLE
主播电台默认只能下载列表第一页的100个文件

### ISSUE THREAD

**Issue by Mackerly** [magicdawn/yun-playlist-downloader#35]
谢谢作者提供的优秀的工具。请问有什么参数能控制下载一个主播的所有节目吗？

**Comment by magicdawn** [comment]
还有超过一页的, 我做漏了...我补一下

**Comment by magicdawn** [comment]
v2.3.0 已发布, see
https://github.com/magicdawn/yun-playlist-downloader/blob/master/CHANGELOG.md#2019-12-28-v230
