### ISSUE TITLE
增加只保留歌单的功能

### ISSUE THREAD

**Issue by maicss** [magicdawn/yun-playlist-downloader#37]
嫌弃他们音质太差，只想要歌单，先谢谢大佬了

**Comment by magicdawn** [comment]
这个截图保存不就行了?

**Comment by maicss** [comment]
想要文档，然后自己去下载。要这样的格式（也就是自带的）：

|歌曲名称|时长|歌手|专辑|
|---|---|---|---|
|bla|bla|bla|bla|

网页上只有1000个，客户端抓包又都加密了……

**Comment by magicdawn** [comment]
```js
var API = require('music-api')
API.getPlaylist('netease', {id: "4984449352", raw: true}).then(ret => global.ret = ret)
```

![image](https://user-images.githubusercontent.com/4067115/80329845-1b137580-8876-11ea-8dd9-d43d5b6eaa0d.png)

时长不知道是哪个字段, 可以自己看看

**Comment by maicss** [comment]
给力！！我去GitHub上搜了半天，咋就没发现这个捏……

**Comment by maicss** [comment]
时长是dt

**Comment by maicss** [comment]
emmm, 这个就是网页上的API，歌单只能拿到1000个歌曲……我还是再找找看有没有其他的方法吧
