### ISSUE TITLE
貌似下载的不是高音质的

### ISSUE THREAD

**Issue by eshion** [magicdawn/yun-playlist-downloader#4]
很好用，很方便！但貌似下载的不是高音质的哦

**Comment by magicdawn** [comment]
从 web 上解析的, 确实不是高音质的~

**Comment by zhaowweny** [comment]
json里面有其他音质的音频ID，可是没有地址，不知道怎么转化的，是什么加密算法吗，还有云音乐 的请求参数也加密了，有没有什么解决的办法？谢谢

**Comment by magicdawn** [comment]
@zhaowweny em...发现有个固定参数是 128000

对比客户端
![image](https://cloud.githubusercontent.com/assets/4067115/13042653/c61d5406-d3fc-11e5-82ba-b4bdb00e1c53.png)

应该是传320000就是 320kbits/s, 下一个版本会使用类似phatomjs的Nightmare去获取传参, 会顺便把音质选择加上~

**Comment by zhaowweny** [comment]
我怎么没看到呢？。。。能弄到无损的不

**Comment by magicdawn** [comment]
@zhaowweny 
![image](https://cloud.githubusercontent.com/assets/4067115/13045675/b65e4e36-d40f-11e5-9997-52a4f7d4db3a.png)

你要是知道对应着无损什么参数, 应该也是可以的...我不知道, 要开VIP然后抓包...

**Comment by magicdawn** [comment]
@zhaowweny 新版本我正在更新哈~稍等

**Comment by magicdawn** [comment]
@eshion @zhaowweny 试试新版本, 重新安装 `npm i yun-playlist-downloader -g`

可以使用 `-q, --quality` 设置音质, 128/192/320 可选, 默认320, 若云音乐那边不存在, 它会自动降级的.

**Comment by magicdawn** [comment]
I'm closing this.

**Comment by zhaowweny** [comment]
@magicdawn.  Ok, great!
