### ISSUE TITLE
要下载自己的喜欢歌单时会要求登录

### ISSUE THREAD

**Issue by ReaderZhang** [magicdawn/yun-playlist-downloader#44]
{
  status: 400,
  body: {
    code: 20001,
    message: '登录后才可查看',
    debugInfo: null,
    data: null,
    failData: null,
    msg: '登录后才可查看'
  },
  cookie: [
   xxxx
  ]
}

**Comment by ReaderZhang** [comment]
能加个登录获取认证的功能吗

**Comment by magicdawn** [comment]
v3.1.0 支持 `--cookie`, see 
https://github.com/magicdawn/yun-playlist-downloader/blob/master/docs/cookie.md#cookie-%E4%BD%BF%E7%94%A8%E8%AF%B4%E6%98%8E
