### ISSUE TITLE
是否能够下载自己的歌单？

### ISSUE THREAD

**Issue by jitre** [magicdawn/yun-playlist-downloader#47]
这边不用cookie下载公开的歌单是正常的，用cookie下载自己的歌单(URL里面换上自己的歌单id)，会报错

当前参数
concurrency:    1
format:         :songName_:singer_:name.:ext
retry-timeout:  3 (分钟)
retry-times:    3 (次)
quality:        320
skip:           true
progress:       true
cover:          true

[cookie] 使用 cookie 文件: /Users/XXX/Desktop/down_music/yun.cookie.txt
{
  status: 502,
  body: {
    code: 502,
    msg: Error: aborted
        at connResetException (node:internal/errors:631:14)
        at TLSSocket.socketCloseListener (node:_http_client:434:19)
        at TLSSocket.emit (node:events:388:22)
        at node:net:666:12
        at TCP.done (node:_tls_wrap:573:7) {
      code: 'ECONNRESET',
      config: [Object],
      request: [ClientRequest],
      response: undefined,
      isAxiosError: true,
      toJSON: [Function: toJSON]
    }
  },
  cookie: []
}

**Comment by magicdawn** [comment]
可以的
![image](https://user-images.githubusercontent.com/4067115/183687017-1c4b7352-db8c-4635-9c86-05cafed340c5.png)

报错是 cookie 不对或没有权限
参照 https://github.com/magicdawn/yun-playlist-downloader/blob/master/docs/cookie.md 设置
