### ISSUE TITLE
如何让下载的歌曲名中包含专辑名

### ISSUE THREAD

**Issue by nichanglan** [magicdawn/yun-playlist-downloader#53]
比如下载歌单：https://music.163.com/#/playlist?id=2047424322
<img width="677" alt="image" src="https://user-images.githubusercontent.com/35494180/220514645-7f1d92ac-a07f-4933-b3b6-858c427e3c8e.png">

我想让我下载下来的歌曲的名字包括专辑名字，大概就是
谢安琪-3/8（新歌+精选）-钟无艳.mp3
吴雨霏-我本人-吴哥窟.mp3
我试了 -f ':name/:singer -:typeText - :songName.:ext'下载名字是
谢安琪 -列表 - 钟无艳.mp3
没有专辑名。该怎么指定参数呢？
麻烦看看了，谢谢！

**Comment by magicdawn** [comment]
暂不支持

**Comment by zhuhuashan** [comment]
**能否处理程支持 无损音质**

**Comment by magicdawn** [comment]
use `:albumName` in v3.3.1

举例
```
~/Music/yun took 2s
$ yun 'https://music.163.com/#/playlist?id=8451519565' -f ':name/:singer - :songName [EP-:albumName].:ext'

当前参数
concurrency:    5
format:         :name/:singer - :songName [EP-:albumName].:ext
retry-timeout:  3 (分钟)
retry-times:    3 (次)
quality:        320
skip:           true
progress:       true
cover:          false

[cookie] 使用 cookie 文件: /Users/magicdawn/Music/yun/yun.cookie.txt
正在下载『test』,请稍候...
ℹ 可下载 1/1 首
✔ 1/1 [==========] 下载成功 test/陈奕迅 - 让我留在你身边 [EP-让我留在你身边] [试听].mp3
下载完成, 耗时1.175 秒
```
