### ISSUE TITLE
歌曲下载不完整 只有30秒

### ISSUE THREAD

**Issue by xingfanxia** [magicdawn/yun-playlist-downloader#54]
![Monosnap netease_music 2023-03-15 04-38-09](https://user-images.githubusercontent.com/8936233/225298129-e455c768-8676-4ddc-ba7e-842cf866d9a2.jpg)
![Monosnap 网易云音乐 2023-03-15 04-38-34](https://user-images.githubusercontent.com/8936233/225298159-9120dacf-e4c8-4cf7-83fb-5d356ab965b9.jpg)
![Monosnap 陈奕迅 - 让我留在你身边 mp3 Info 2023-03-15 04-38-44](https://user-images.githubusercontent.com/8936233/225298194-1e832efd-d6c7-4ce1-bf8b-91de506b75fd.jpg)
![netease_music 2023-03-15 04-38-51](https://user-images.githubusercontent.com/8936233/225298216-49b00cf4-b2a7-478e-8959-1408f3628d34.jpg)

**Comment by bao3** [comment]
这是因为部分 VIP 歌曲，只能下载 30s。除非更换 API，不过这个 repo 似乎并不支持私有 API

**Comment by magicdawn** [comment]
> 这是因为部分 VIP 歌曲，只能下载 30s
感谢解答!

**Comment by magicdawn** [comment]
```
~/Music/yun took 2s
$ yun 'https://music.163.com/#/playlist?id=8451519565'

当前参数
concurrency:    5
format:         :name/:singer - :songName.:ext
retry-timeout:  3 (分钟)
retry-times:    3 (次)
quality:        320
skip:           true
progress:       true
cover:          false

[cookie] 使用 cookie 文件: /Users/magicdawn/Music/yun/yun.cookie.txt
正在下载『test』,请稍候...
ℹ 可下载 1/1 首
✔ 1/1 [==========] 下载跳过 test/陈奕迅 - 让我留在你身边 [试听].mp3
下载完成, 耗时0.772 秒
```

已加上 `[试听]` 标识.
https://github.com/Binaryify/NeteaseCloudMusicApi/issues/1713

**Comment by bao3** [comment]
我注意到，使用子 cookie，但我明明是会员，VIP 也不能下载，可是在 web 上我是可以完整听完的。发自我的 iPhone在 2023年6月2日，16:52，Tao ***@***.***> 写道：﻿
~/Music/yun took 2s
$ yun 'https://music.163.com/#/playlist?id=8451519565'

当前参数
concurrency:    5
format:         :name/:singer - :songName.:ext
retry-timeout:  3 (分钟)
retry-times:    3 (次)
quality:        320
skip:           true
progress:       true
cover:          false

[cookie] 使用 cookie 文件: /Users/magicdawn/Music/yun/yun.cookie.txt
正在下载『test』,请稍候...
ℹ 可下载 1/1 首
✔ 1/1 [==========] 下载跳过 test/陈奕迅 - 让我留在你身边 [试听].mp3
下载完成, 耗时0.772 秒

已加上 [试听] 标识.
Binaryify/NeteaseCloudMusicApi#1713

**Comment by magicdawn** [comment]
那就是 VIP 用别的 API 了. 我们等上游修复https://github.com/Binaryify/NeteaseCloudMusicApi 修复 !!!!!!

**Comment by magicdawn** [comment]
close by v3.5.0, #57 related.
