### ISSUE TITLE
使用VIP的cookie后依然返回30秒（解决）

### ISSUE THREAD

**Issue by qinfengge** [magicdawn/yun-playlist-downloader#57]
![image](https://github.com/magicdawn/yun-playlist-downloader/assets/35164697/df6ed039-4db2-479d-a55e-cf4fe963ebf9)
另外能否支持自定义api，我之前的api好像是能下flac无损的
![image](https://github.com/magicdawn/yun-playlist-downloader/assets/35164697/93ebcda0-cd58-4ffd-a54a-be154067c384)

**Comment by qinfengge** [comment]
### 解决30秒限制并默认下载flac无损格式
step 1: 找到npm安装依赖的路径
![image](https://github.com/magicdawn/yun-playlist-downloader/assets/35164697/cb16841f-0fc0-414e-a9ee-c45fd0c45f9a)
step 2: 修改此文件中获取音乐路径的方法
```js
async function songUrl(ids) {
  const singleRequest = async (id) => {
    const res = await Api.song_url({ id, cookie: COOKIE_CONTENT });
    const infos = res.body.data;
    return infos;
  };
```
保存，重试即可。
原理为获取songUrl时使用cookie指定，并取消br码率设置使用默认的最高码率
![image](https://github.com/magicdawn/yun-playlist-downloader/assets/35164697/a6a9be94-dd6c-4381-b3a9-552a106794c6)

### 扩展
可使用新版接口获取**超清母带**码率
![image](https://github.com/magicdawn/yun-playlist-downloader/assets/35164697/a1e3bbb6-e23d-448c-84b5-762a2206652a)

**Comment by wujiezero** [comment]
> ### 解决30秒限制并默认下载flac无损格式
> step 1: 找到npm安装依赖的路径 ![image](https://user-images.githubusercontent.com/35164697/262547092-cb16841f-0fc0-414e-a9ee-c45fd0c45f9a.png) step 2: 修改此文件中获取音乐路径的方法
> 
> ```js
> async function songUrl(ids) {
>   const singleRequest = async (id) => {
>     const res = await Api.song_url({ id, cookie: COOKIE_CONTENT });
>     const infos = res.body.data;
>     return infos;
>   };
> ```
> 
> 保存，重试即可。 原理为获取songUrl时使用cookie指定，并取消br码率设置使用默认的最高码率 ![image](https://user-images.githubusercontent.com/35164697/262547608-a6a9be94-dd6c-4381-b3a9-552a106794c6.png)
> 
> ### 扩展
> 可使用新版接口获取**超清母带**码率 ![image](https://user-images.githubusercontent.com/35164697/262547809-a1e3bbb6-e23d-448c-84b5-762a2206652a.png)

你好，我参照这个改了js文件，还是默认下载320的mp3文件，请问还需要改哪里吗

**Comment by qinfengge** [comment]
注意查看这一行  const res = await Api.song_url({ id, cookie: COOKIE_CONTENT });
删除原来参数中的br，以使用默认最高音质

Billy ***@***.***> 於 2023年8月23日 週三 下午5:38寫道：

**Comment by magicdawn** [comment]
咦~ 原来 cookie 只在 playlist-detail 用了
