### ISSUE TITLE
报错await  SyntaxError: Unexpected reserved word

### ISSUE THREAD

**Issue by JamesLyn** [magicdawn/yun-playlist-downloader#64]
yun 'https://sg.music.163.com/#/album?id=2732694'
file:///usr/local/lib/node_modules/yun-playlist-downloader/dist/bin.js:108
var argv = await parser.argv;
           ^^^^^

SyntaxError: Unexpected reserved word
    at Loader.moduleStrategy (internal/modules/esm/translators.js:133:18)
    at async link (internal/modules/esm/module_job.js:42:21)

**Comment by magicdawn** [comment]
use node lts 

https://nodejs.org/en/download
![image](https://github.com/magicdawn/yun-playlist-downloader/assets/4067115/456d6004-3dbf-4f78-8e59-9a7facbf7911)

![image](https://github.com/magicdawn/yun-playlist-downloader/assets/4067115/47fbf7ce-1e50-45d7-b4ba-81e4c0f9511b)
